### ISSUE TITLE
Add additional Sections(steps)-Tax-Form

### ISSUE THREAD

**Issue by dioscarr** [dioscarr/pnl#1]
# Task 
Good morning Dioscar, you've done great work. below are my comments for the form area. When I write "section" that means it's own page/step

- [ ] Section 1
- [ ] Section 2
- [ ] Section 3 - Conditional section for the spouse information
- [ ] Section 4
- [ ] Section 5
*** 
  ![image](https://user-images.githubusercontent.com/6876354/103302382-826b6180-49d1-11eb-9bb8-9d76d8d15216.png)

***

- [ ] Split this Step  ![image](https://user-images.githubusercontent.com/6876354/103302389-85fee880-49d1-11eb-968c-f6f1d6328234.png)

***

![image](https://user-images.githubusercontent.com/6876354/103302395-8a2b0600-49d1-11eb-99dd-572a64c0501b.png)

***

- [x]  for the portion next to the social media icons, you can delete the dummy text and center the social media icons

- [x] I'll get the address and phone number to put under the PNL tax logo

**Comment by ctoonzmk** [comment]
# Security and Protection
**All titles must be Capitalized**
- [x] IRS Approved
- [x] The Human Touch
- [x] Double Protection
- [x] Safe and Secure
- [x] Permission Only

![image](https://user-images.githubusercontent.com/15790207/103303792-e4799600-49d4-11eb-98da-3e3f3056cb99.png)

**Comment by dioscarr** [comment]
Nice!  👍 @ctoonzmk
